spring:
  datasource:
    dynamic:
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/mysql-plus?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true
          #url: jdbc:mysql://localhost:3306/mysql-plus?serverTimezone=Asia/ShanghaiuseUnicode=true&&useSSL=false&characterEncoding=utf8&characterSetResults=utf8
          username: root
          password: test
        slave:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/mysql-plus-slave?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true
          username: root
          password: test
      primary: master # 设置默认的数据源或者数据源组. 默认值即为master.
      strict: false #  设置严格模式，默认false不启动.。若设置为true，则在未匹配到指定数据源时会抛出异常。若设置为false，则在未匹配到指定数据源时会使用默认数据源。
